// Core session management

// Extension system
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type {
	AfterProviderResponseEvent,
	AgentActivityOutcome,
	AgentBeforeSettleEvent,
	AgentBeforeSettleEventResult,
	AgentEndEvent,
	AgentSettledEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderHeadersEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BoundaryContextPreview,
	BoundaryResult,
	BoundaryState,
	BuildSystemPromptOptions,
	CacheWarmingDecision,
	CacheWarmingDecisionEvent,
	CacheWarmingDecisionEventResult,
	CacheWarmingStatus,
	CompactionEntryDraft,
	CompactOptions,
	ContextEditEntryDraft,
	ContextEvent,
	ContextEventResult,
	ContextUsage,
	ContextWithSystemEvent,
	CustomEntryDraft,
	CustomMessageEntryDraft,
	CustomToolCallEvent,
	EditToolCallEvent,
	EntryRenderer,
	EntryRenderOptions,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionVirtualModel,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InlineExtension,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MarkdownTransformContext,
	MarkdownTransformer,
	MessageEndEvent,
	MessageEndEventResult,
	MessageRenderer,
	MessageRenderOptions,
	MessageStartEvent,
	MessageUpdateEvent,
	ModelSelectEvent,
	ModelSelectSource,
	NormalizedBuildSystemPromptOptions,
	PackageManager,
	PathMetadata,
	PowerShellToolCallEvent,
	ProgressCallback,
	ProgressEvent,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ProviderStreamEvent,
	ReadonlyFooterDataProvider,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	ResolvedPaths,
	ResolvedResource,
	ResourceCollision,
	ResourceDiagnostic,
	ResourceLoader,
	ResourcesDiscoverEvent,
	ResourcesDiscoverResult,
	SessionBeforeCompactEvent,
	SessionBeforeCompactResult,
	SessionBeforeForkEvent,
	SessionBeforeForkResult,
	SessionBeforeSwitchEvent,
	SessionBeforeSwitchResult,
	SessionBeforeTreeEvent,
	SessionBeforeTreeResult,
	SessionBoundaryDraft,
	SessionCompactEvent,
	SessionCompactFailedEvent,
	SessionInfoChangedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	Theme,
	ThinkingLevelSelectEvent,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionEndEvent,
	ToolExecutionMode,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	ToolResultEventResult,
	TurnEndEvent,
	TurnEndEventResult,
	TurnStartEvent,
	UIPromptEndEvent,
	UIPromptKind,
	UIPromptStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "@earendil-works/pi-core";
// Compaction
// SDK for programmatic usage
// Skills
// Tools
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	type BranchPreparation,
	type BranchSummaryEntry,
	type BranchSummaryResult,
	buildContextEntries,
	buildSessionContext,
	buildSessionProjection,
	type CacheWarmingMode,
	type CollectEntriesResult,
	type CompactionEntry,
	type CompactionModelOverride,
	type CompactionResult,
	type CompactionSettings,
	type ContextEditableContent,
	type ContextEditEntry,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	type CreateModelRuntimeOptions,
	CredentialSynchronizationError,
	type CredentialSynchronizationOperation,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	convertToLlm,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	createBashToolDefinition,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createEditToolDefinition,
	createEventBus,
	createExtensionRuntime,
	createFindTool,
	createFindToolDefinition,
	createGrepTool,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLocalPowerShellOperations,
	createLsTool,
	createLsToolDefinition,
	createPowerShellTool,
	createPowerShellToolDefinition,
	createReadOnlyTools,
	createReadTool,
	createReadToolDefinition,
	createSyntheticSourceInfo,
	createWriteTool,
	createWriteToolDefinition,
	DEFAULT_COMPACTION_SETTINGS,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	DefaultPackageManager,
	type DefaultProjectTrust,
	DefaultResourceLoader,
	defineTool,
	discoverAndLoadExtensions,
	type EditDiffResult,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type EventBus,
	type EventBusController,
	ExtensionRunner,
	estimateTokens,
	type FileEntry,
	type FileOperations,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	type FullscreenExitOutput,
	findCutPoint,
	findTurnStartIndex,
	formatSize,
	formatSkillsForPrompt,
	type GenerateBranchSummaryOptions,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	generateBranchSummary,
	generateDiffString,
	generateSummary,
	generateSummaryWithUsage,
	generateUnifiedPatch,
	getLastAssistantUsage,
	getLatestCompactionEntry,
	hasTrustRequiringProjectResources,
	type ImageSettings,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isPowerShellToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	loadProjectContextFiles,
	loadSkills,
	loadSkillsFromDir,
	type ModelChangeEntry,
	type ModelCycleResult,
	ModelRegistry,
	type ModelRoute,
	type ModelRouteReason,
	type ModelRouteRequest,
	ModelRuntime,
	type ModelRuntimeAuthOverrides,
	type ModelScopeDiagnostic,
	migrateSessionEntries,
	type NewSessionOptions,
	type PackageSource,
	type ParsedSkillBlock,
	type PowerShellOperations,
	type PowerShellSpawnContext,
	type PowerShellSpawnHook,
	type PowerShellToolDetails,
	type PowerShellToolInput,
	type PowerShellToolOptions,
	type ProjectedSessionEntry,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
	type PromptOptions,
	type PromptTemplate,
	parseSessionEntries,
	parseSkillBlock,
	prepareBranchEntries,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ResolveCliModelResult,
	type ResolveModelScopeResult,
	type RetrySettings,
	readStoredCredential,
	resolveCliModel,
	resolveModelScopeWithDiagnostics,
	type ScopedModel,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type SessionProjection,
	type SessionStats,
	type SessionTreeNode,
	SettingsManager,
	type SettingsManagerCreateOptions,
	type Skill,
	type SkillFrontmatter,
	serializeConversation,
	sessionEntryToContextMessages,
	shouldCompact,
	type ThinkingLevelChangeEntry,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	type TuiMode,
	truncateHead,
	truncateLine,
	truncateTail,
	VIRTUAL_MODEL_STATE_ENTRY,
	type VirtualModelDefinition,
	type VirtualModelStateData,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "@earendil-works/pi-core";
export { type Args, parseArgs } from "./cli/args.ts";
// Config paths
export {
	CONFIG_DIR_NAME,
	getAgentDir,
	getDocsPath,
	getExamplesPath,
	getPackageDir,
	getReadmePath,
	VERSION,
} from "./config.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type JsonAgentSessionEvent,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcResponse,
	type RpcSessionState,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	type CustomEditorOptions,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme as TerminalTheme,
	type ThemeAppearance,
	type ThemeBg,
	type ThemeColor,
	type ThemeStyle,
	type ThemeToken,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
export { detectSupportedImageMimeTypeFromFile } from "./utils/mime.ts";
// Shell utilities
export { getPowerShellConfig, getShellConfig } from "./utils/shell.ts";
